<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "Blog Neuropsic\u00f3logo Danilo Damata ",
    "slogan": "Bem-vindo ao Blog Neuropsic\u00f3logo Danilo Damata ",
    "description": "Sou Danilo, Psico\u0301logo, Neuropsico\u0301logo e Professor Acade\u0302mico Se voc\u00ea busca entender melhor suas habilidades cognitivas, emocionais e desafios, estou aqui para ajudar!  Avalio sintomas relacionados ao TEA \u2013 Autismo, TDAH, Desenvolvimento Intelectual, Dificuldades de Aprendizagem e analiso quadros com suspeita de Doenc\u0327as Neurodegenerativas (Alzheimer, Deme\u0302ncias, AVC), Personalidade e Super dotac\u0327a\u0303o.",
    "footer": "Copyright \u00a9 2025",
    "itemsPerPage": 6,
    "language": "pt_BR",
    "locale": "pt_BR",
    "timezone": "America\/Sao_Paulo",
    "theme": "nimbus",
    "adminTheme": "booty",
    "homepage": "",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "",
    "url": "https:\/\/danilodamata.com\/blog\/",
    "emailFrom": "no-reply@danilodamata.com",
    "orderBy": "date",
    "currentBuild": 20240806,
    "twitter": "",
    "facebook": "",
    "codepen": "",
    "github": "",
    "instagram": "",
    "gitlab": "",
    "linkedin": "",
    "xing": "",
    "telegram": "",
    "dateFormat": "d\/M\/y H:m",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false,
    "mastodon": "",
    "dribbble": "",
    "vk": "",
    "thumbnailWidth": 400,
    "thumbnailHeight": 400,
    "thumbnailQuality": 100,
    "markdownParser": true,
    "customFields": "[]",
    "logo": "Blog Neuropsic\u00f3logo Danilo Damata .png"
}